const inputName = document.getElementById('add-item-name')
const inputAmount = document.getElementById('add-item-amount')
const inputPrice = document.getElementById('add-item-price')
const inputEmpty = document.getElementById('empty-mylist')
const confirmEmpty = document.querySelector('.btn-empty')
const inputDelete = document.getElementById('delete-mylist')
const confirmDelete = document.querySelector('.btn-delete')
const newItem = document.querySelector('.item-list')
const confirmItem = document.querySelector('.btn-add')
const inputSearch = document.getElementById('mySearch')

let div = document.querySelector('#overview')
let addModal = document.querySelector('.modal-medium')
let emptyModal = document.querySelector('.modal-small')
let deleteModal = document.querySelector('.modal-delete')
let emptyMessage = document.querySelector('.js-clear-feedback')
let deleteMessage = document.querySelector('.js-delete-feedback')
let total = document.querySelector('.total-price')
let validateName = document.querySelector('.js-name-feedback')
let validateOnlyName = document.querySelector('.js-name-error')
let validateAmount = document.querySelector('.js-amount-feedback')
let validatePrice = document.querySelector('.js-price-feedback')
let filterItem = document.getElementsByTagName('li')
let tempId
